DEFAULT_THREAD_COUNT = 1
DEFAULT_TIME_STEP = 0.0
DEFAULT_SIMULATION_TIME = 0.0
DEFAULT_TEMPERATURE = 0.0
DEFAULT_PRESSURE = 0.0

DEFAULT_ITERATIONS = 1000
DEFAULT_CONVERGENCE_TOLERANCE = 1e-20
DEFAULT_OUTPUT_FREQUENCY = 1
DEFAULT_NUM_BLOCKS = 30
DEFAULT_BLOCK_SIZE = 1
DEFAULT_MAX_RESTARTS = 20
DEFAULT_MAX_ITERATIONS = 1000
DEFAULT_FEM_ACCURACY = 3
DEFAULT_CUBIC_GRID_SIZE = 5.0
