from constants import *
from util import get_thread_count

LIMIT_CONFIG_MIN_THREAD_COUNT = 1
LIMIT_CONFIG_MAX_THREAD_COUNT = get_thread_count()

LIMIT_CONFIG_MIN_TIME_STEP = SIMULATION_LIMIT_MIN_TIME
LIMIT_CONFIG_MAX_TIME_STEP = float('inf')

LIMIT_CONFIG_MIN_SIMULATION_TIME = SIMULATION_LIMIT_MIN_TIME
LIMIT_CONFIG_MAX_SIMULATION_TIME = float('inf')

LIMIT_CONFIG_MIN_TEMPERATURE = 0.0
LIMIT_CONFIG_MAX_TEMPERATURE = float('inf')

LIMIT_CONFIG_MIN_PRESSURE = 0.0
LIMIT_CONFIG_MAX_PRESSURE = SIMULATION_LIMIT_MAX_PRESSURE

LIMIT_CONFIG_MIN_ITERATIONS = 1
LIMIT_CONFIG_MAX_ITERATIONS = 100000

LIMIT_CONFIG_MIN_CONVERGENCE_TOLERANCE = 1e-50
LIMIT_CONFIG_MAX_CONVERGENCE_TOLERANCE = 1e-1

LIMIT_CONFIG_MIN_OUTPUT_FREQUENCY = 1
LIMIT_CONFIG_MAX_OUTPUT_FREQUENCY = 1000

LIMIT_CONFIG_MIN_NUM_BLOCKS = 1
LIMIT_CONFIG_MAX_NUM_BLOCKS = 1000

LIMIT_CONFIG_MIN_BLOCK_SIZE = 1
LIMIT_CONFIG_MAX_BLOCK_SIZE = 1000

LIMIT_CONFIG_MIN_MAX_RESTARTS = 0
LIMIT_CONFIG_MAX_MAX_RESTARTS = 1000

LIMIT_CONFIG_MIN_FEM_ACCURACY = 1
LIMIT_CONFIG_MAX_FEM_ACCURACY = 20

LIMIT_CONFIG_MIN_CUBIC_GRID_SIZE = 0.1
LIMIT_CONFIG_MAX_CUBIC_GRID_SIZE = 1000.0
