ITERATIVE_SOLVER_NAMES = [
    "CG", "Block CG", "GMRES", "Block GMRES", "LSQR", "MINRES"
]

ITERATIVE_SOLVER_MAX_ITERATION_FIELD_NAME = "maxIterations"
ITERATIVE_SOLVER_CONVERGENCE_TOLERANCE_FIELD_NAME = "convergenceTolerance"
ITERATIVE_SOLVER_OUTPUT_FREQUENCY_FIELD_NAME = "outputFrequency"
ITERATIVE_SOLVER_NUM_BLOCKS_FIELD_NAME = "numBlocks"
ITERATIVE_SOLVER_BLOCK_SIZE_FIELD_NAME = "blockSize"
ITERATIVE_SOLVER_MAX_RESTARTS_FIELD_NAME = "maxRestarts"
ITERATIVE_SOLVER_FLEXIBLE_GMRES_FIELD_NAME = "flexibleGMRES"
ITERATIVE_SOLVER_ORTHOGONALIZATION_FIELD_NAME = "orthogonalization"
ITERATIVE_SOLVER_ADAPTIVE_BLOCK_SIZE_FIELD_NAME = "adaptiveBlockSize"
ITERATIVE_SOLVER_CONVERGENCE_TEST_FREQUENCY_FIELD_NAME = "convergenceTestFrequency"

ITERATIVE_SOLVER_VISIBLE_PARAMETERS = {
    "CG": [
        ITERATIVE_SOLVER_MAX_ITERATION_FIELD_NAME,
        ITERATIVE_SOLVER_CONVERGENCE_TOLERANCE_FIELD_NAME,
        ITERATIVE_SOLVER_OUTPUT_FREQUENCY_FIELD_NAME,
        ITERATIVE_SOLVER_BLOCK_SIZE_FIELD_NAME
    ],
    "Block CG": [
        ITERATIVE_SOLVER_MAX_ITERATION_FIELD_NAME,
        ITERATIVE_SOLVER_CONVERGENCE_TOLERANCE_FIELD_NAME,
        ITERATIVE_SOLVER_OUTPUT_FREQUENCY_FIELD_NAME,
        ITERATIVE_SOLVER_BLOCK_SIZE_FIELD_NAME,
        ITERATIVE_SOLVER_ADAPTIVE_BLOCK_SIZE_FIELD_NAME
    ],
    "GMRES": [
        ITERATIVE_SOLVER_MAX_ITERATION_FIELD_NAME,
        ITERATIVE_SOLVER_CONVERGENCE_TOLERANCE_FIELD_NAME,
        ITERATIVE_SOLVER_OUTPUT_FREQUENCY_FIELD_NAME,
        ITERATIVE_SOLVER_NUM_BLOCKS_FIELD_NAME,
        ITERATIVE_SOLVER_MAX_RESTARTS_FIELD_NAME,
        ITERATIVE_SOLVER_ORTHOGONALIZATION_FIELD_NAME,
        ITERATIVE_SOLVER_FLEXIBLE_GMRES_FIELD_NAME
    ],
    "Block GMRES": [
        ITERATIVE_SOLVER_MAX_ITERATION_FIELD_NAME,
        ITERATIVE_SOLVER_CONVERGENCE_TOLERANCE_FIELD_NAME,
        ITERATIVE_SOLVER_OUTPUT_FREQUENCY_FIELD_NAME,
        ITERATIVE_SOLVER_NUM_BLOCKS_FIELD_NAME,
        ITERATIVE_SOLVER_MAX_RESTARTS_FIELD_NAME,
        ITERATIVE_SOLVER_ORTHOGONALIZATION_FIELD_NAME,
        ITERATIVE_SOLVER_ADAPTIVE_BLOCK_SIZE_FIELD_NAME,
        ITERATIVE_SOLVER_CONVERGENCE_TEST_FREQUENCY_FIELD_NAME
    ],
    "LSQR": [
        ITERATIVE_SOLVER_MAX_ITERATION_FIELD_NAME,
        ITERATIVE_SOLVER_CONVERGENCE_TOLERANCE_FIELD_NAME,
        ITERATIVE_SOLVER_OUTPUT_FREQUENCY_FIELD_NAME
    ],
    "MINRES": [
        ITERATIVE_SOLVER_MAX_ITERATION_FIELD_NAME,
        ITERATIVE_SOLVER_CONVERGENCE_TOLERANCE_FIELD_NAME,
        ITERATIVE_SOLVER_OUTPUT_FREQUENCY_FIELD_NAME
    ]
}
